version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vd_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/code/downloads
      - ./data/cookies:/code/data/cookies

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vd_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
