version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vd_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/code/downloads
      - ./data:/code/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vd_frontend
    restart: unless-stopped
    depends_on:
      - backend

  caddy:
    image: caddy:alpine
    container_name: vd_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend

volumes:
  caddy_data:
  caddy_config:
